### ISSUE TITLE
Colab custom image demo error

### ISSUE THREAD

**Issue by name8997** [nex-mpi/nex-code#1]
Hello, Thank you for your masterpiece.

The following error occurs when I train your model from colab to custom image.

My video's resolution is 1280 x 720

How to solve that?

Thanks.

--------------------------------------------------------------------------------------------

Loaded data/demo 1.435987851575115 25.984873491396872
recentered (3, 4)
Overriding offset 200-> 80
dmin = 7.938341, dmax = 20.183123, invz = 0, offset = 80
TRAINING IMAGES: 37
VALIDATE IMAGES: 6
Basis Network: DataParallel(
  (module): ReluMLP(
    (activation): LeakyReLU(negative_slope=0.01)
    (seq1): Sequential(
      (0): Linear(in_features=12, out_features=64, bias=True)
      (1): LeakyReLU(negative_slope=0.01)
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): LeakyReLU(negative_slope=0.01)
      (4): Linear(in_features=64, out_features=8, bias=True)
    )
  )
)
Mpi Size: torch.Size([12, 3, 385, 560])
All combined layers: 72
[ 7.93834066  8.11080238  8.2832641   8.45572582  8.62818754  8.80064925
  8.97311097  9.14557269  9.31803441  9.49049613  9.66295784  9.83541956
 10.00788128 10.180343   10.35280471 10.52526643 10.69772815 10.87018987
 11.04265159 11.2151133  11.38757502 11.56003674 11.73249846 11.90496018
 12.07742189 12.24988361 12.42234533 12.59480705 12.76726877 12.93973048
 13.1121922  13.28465392 13.45711564 13.62957735 13.80203907 13.97450079
 14.14696251 14.31942423 14.49188594 14.66434766 14.83680938 15.0092711
 15.18173282 15.35419453 15.52665625 15.69911797 15.87157969 16.04404141
 16.21650312 16.38896484 16.56142656 16.73388828 16.90634999 17.07881171
 17.25127343 17.42373515 17.59619687 17.76865858 17.9411203  18.11358202
 18.28604374 18.45850546 18.63096717 18.80342889 18.97589061 19.14835233
 19.32081405 19.49327576 19.66573748 19.8381992  20.01066092 20.18312263]
Using inverse depth: False, Min depth: 7.938340663909912, Max depth: 20.183122634887695
Layer of MLP: 6
Hidden Channel of MLP: 128
Main Network DataParallel(
  (module): VanillaMLP(
    (activation): LeakyReLU(negative_slope=0.01)
    (seq1): Sequential(
      (0): Linear(in_features=50, out_features=128, bias=True)
      (1): LeakyReLU(negative_slope=0.01)
      (2): Linear(in_features=128, out_features=128, bias=True)
      (3): LeakyReLU(negative_slope=0.01)
      (4): Linear(in_features=128, out_features=128, bias=True)
      (5): LeakyReLU(negative_slope=0.01)
      (6): Linear(in_features=128, out_features=128, bias=True)
      (7): LeakyReLU(negative_slope=0.01)
      (8): Linear(in_features=128, out_features=128, bias=True)
      (9): LeakyReLU(negative_slope=0.01)
      (10): Linear(in_features=128, out_features=25, bias=True)
    )
  )
)
"train.py" in <module>
  785:  train()
  train.py
"train.py" in train
  576:  start_epoch = loadFromCheckpoint(ckpt, model, optimizer)
  train.py
"train.py" in loadFromCheckpoint
  743:  model.load_state_dict(checkpoint['model_state_dict'])
  train.py
"module.py" in load_state_dict
 1224:  self.__class__.__name__, "\n\t".join(error_msgs)))
  /usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py
RuntimeError: Error(s) in loading state_dict for Network:
	size mismatch for mpi_c: copying a param with shape torch.Size([12, 3, 460, 560]) from checkpoint, the shape in current model is torch.Size([12, 3, 385, 560]).
CPU times: user 38.2 ms, sys: 8.82 ms, total: 47.1 ms
Wall time: 5.15 s

**Comment by pureexe** [comment]
```
576: start_epoch = loadFromCheckpoint(ckpt, model, optimizer)
```

From your error, it tried to load the checkpoint which has unmatched size

Maybe you train something else before your custom image.

Please try to factory reset runtime

![](https://i.imgur.com/bk71LSa.png)

**Comment by name8997** [comment]
Thank you! 

It work!
