### ISSUE TITLE
Webplayer/ Demo shows black screen

### ISSUE THREAD

**Issue by chris-aeviator** [nex-mpi/nex-code#11]
When visiting https://nex-mpi.github.io/viewer/viewer.html?scene=https://pureexe.github.io/food/1008 I cannot see any image being rendered. I'm using Firefox v88 on arch linux. In chrome the application just crashes for me.

![grafik](https://user-images.githubusercontent.com/11522213/117409611-a99ee600-af11-11eb-8158-b9aeb8680758.png)

**Comment by pureexe** [comment]
Please try to open this link instead. Is it work for you? 
https://nex-mpi.github.io/viewer/viewer.html?scene=https://pureexe.github.io/food/640

What is your machine spec? 
I suspect that memory. (RAM / VRAM) is too small for storing the MPI.

**Comment by chris-aeviator** [comment]
@pureexe  thanks - this link works. I'm running this off a X1 Carbon Notebook but with the second link I'll get also higher FPS (~40). Will try in an hr on a GPU machine, thanks for the quick response. 

EDIT: 16 GB of RAM here
