### ISSUE TITLE
The question about training and predict

### ISSUE THREAD

**Issue by MarcoG5** [nex-mpi/nex-code#12]
Hello, thank you for your great work!

I wonder whether the model trained in one scene can be applied to other scenes. 
Because when I try to applied a model on other datasets, it seems that the output frames are still the trained scene itself. 
Is this because I made a mistake when I ran the code, or was it designed this way?
 
Thanks.

**Comment by pureexe** [comment]
No, you need to retrain NeX every time when scene changes.

**Comment by MarcoG5** [comment]
> No, you need to retrain NeX every time when scene changes.

Thank you for your reply!
