### ISSUE TITLE
Pose convention of nerf_pose_to_ours.

### ISSUE THREAD

**Issue by ybbbbt** [nex-mpi/nex-code#13]
Hi,

Thanks for sharing this great work!
I'm confused about the pose convention of the following lines in `def nerf_pose_to_ours(*)`. Could you explain the geometric meaning behind it?

https://github.com/nex-mpi/nex-code/blob/eeff38c712ac9a665f09d7c2a3fdf48ae83f4693/utils/sfm_utils.py#L323-L325

**Comment by pureexe** [comment]
NeX is using **OpenCV** convention while NeRF and LLFF are using **OpenGL** convention.

![image](https://user-images.githubusercontent.com/1303847/119395403-a7a09980-bcfd-11eb-83a2-8d3d03ef1e9e.png)

( Graphic taken from [What are the coordinates?](https://medium.com/comerge/what-are-the-coordinates-225f1ec0dd78) )

# How to convert from NeRF (OpenGL) pose to NeX (Ours)

The orange point show below is the same point.  However, the different conventions make the value different. 

For OpenCV to OpenGL, we have to Flip the axis.

The orange point in OpenCV [x,y,z] become [x,-y,-z] in OpenGL convention.

![image](https://user-images.githubusercontent.com/1303847/119397343-31516680-bd00-11eb-91b6-c2dc89fdcc61.png)




We can multiply this 3x3 matrix to convert the coordinate of the point between OpenCV and OpenGL convention

![image](https://user-images.githubusercontent.com/1303847/119397910-00256600-bd01-11eb-8b7a-f670c352ec53.png)

Let's R be a 3x3 rotation matrix such that 

![image](https://user-images.githubusercontent.com/1303847/119398271-89d53380-bd01-11eb-81b3-eefb09f10c37.png)


We will do these following step:

1. Convert the point [x,y,z] into OpenGL coordinate 
2. Rotate (Apply) in OpenGL coordinate with the rotation matrix
3. Convert the point  into OpenCV coordinate


![image](https://user-images.githubusercontent.com/1303847/119399105-afaf0800-bd02-11eb-802e-3f2315996282.png)


Let's do step by step multiplication.

![image](https://user-images.githubusercontent.com/1303847/119399760-7b881700-bd03-11eb-9853-8cf275d8bda7.png)

Here you get the line 324-325

https://github.com/nex-mpi/nex-code/blob/eeff38c712ac9a665f09d7c2a3fdf48ae83f4693/utils/sfm_utils.py#L324-L325

For line 323, you just flip the y-axis and z-axis of the camera center. 

https://github.com/nex-mpi/nex-code/blob/eeff38c712ac9a665f09d7c2a3fdf48ae83f4693/utils/sfm_utils.py#L323


I hope you understand this explanation. 

Feel free to ask if you have a question 😄😄😄

**Comment by ybbbbt** [comment]
Thank you so much for the quick and detailed reply!
I think I have fully understand this convension.

**Comment by SSground** [comment]
<div class="f6 px-3 py-2 lh-condensed border-bottom color-bg-secondary" style="box-sizing: border-box; border-bottom: 1px solid var(--color-border-primary) !important; background-color: var(--color-bg-secondary) !important; padding: 8px 16px !important; font-size: 12px !important; line-height: 1.25 !important; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="mb-0 text-bold" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; font-weight: 600 !important;"><a href="https://github.com/nex-mpi/nex-code/blob/eeff38c712ac9a665f09d7c2a3fdf48ae83f4693/utils/sfm_utils.py#L323-L325" style="box-sizing: border-box; background-color: initial; color: var(--color-text-link); text-decoration: none;">nex-code/utils/sfm_utils.py</a></p><p class="mb-0 color-text-tertiary" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: var(--color-text-tertiary) !important;">Lines 323 to 325 in<span>&nbsp;</span><a data-pjax="true" class="commit-tease-sha" href="https://github.com/nex-mpi/nex-code/commit/eeff38c712ac9a665f09d7c2a3fdf48ae83f4693" style="box-sizing: border-box; background-color: initial; color: var(--color-text-primary); text-decoration: none; display: inline-block; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, monospace; font-size: 12px;">eeff38c</a></p></div><div itemprop="text" class="blob-wrapper blob-wrapper-embedded data" style="box-sizing: border-box; overflow: auto; max-height: 240px; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"> center[1:] *= -1  R[1:, 0] *= -1  R[0, 1:] *= -1 </div>

If I want to use nerf's pose convention, just delete these three lines
