### ISSUE TITLE
Pre-trained models?

### ISSUE THREAD

**Issue by jason718** [nex-mpi/nex-code#15]
Will there be plans to release the pre-trained models on all three dataset?

**Comment by pureexe** [comment]
The model is scene-specific. 

You have to retrain the model every time when the scene change. 

10 space dataset scenes + 8 Real forward dataset scenes + 8 shiny dataset scenes =  26 models.

We don't have a plan to release a pre-train model.

**Comment by jason718** [comment]
Are all the hyper-parameters (LR, epochs, etc.) set the same for these 26 scenes?

If not, could you please share the training scripts?

**Comment by pureexe** [comment]
Hyperparameter (LR, epoch) is the same across 26 scenes. 

Other parameters also the same across the scene and already set as default arguments in `train.py`

The different part (dmin, dmax, offset) script will recognize `planes.txt` and `pose_bounds.npy` then load the correct setting automatically. 

To replicate the training run. 
`python train.py -scene ${PATH_TO_SCENE} -model_dir ${MODEL_TO_SAVE_CHECKPOINT} -cv2resize`

please note that you need `-cv2resize` to make the score to be the same as shown on the paper.

**Comment by derrick-xwp** [comment]
Hey, I did not use -cv2resize, but the PSNR is better than that in paper. So which one shoule I take for comparisons?
