### ISSUE TITLE
Is there any requirements for the training data or args?

### ISSUE THREAD

**Issue by LYHTHU** [nex-mpi/nex-code#2]
I take 12 casual photos of the same scene with a little difference in position and angles and trained with the Colab demo.  The training procedure(the size is 400, training for 40 epochs) seems to be fine. However, the results are extremely blurred, and cannot see anything. I am not sure if there are any requirements for the input images.

**Comment by pureexe** [comment]
Could you send the images that you tried?  

You may have to increase the number of epochs.

The cake dataset has about 50 images which are 50 x 40 epochs = 2000 iterations. With 12 images, it has only 12x40 = 480 iterations.  

Quality will improve over time. The result that shows on the website is trained with 4000 epochs.

**Comment by LYHTHU** [comment]
> Could you send the images that you tried?
> 
> You may have to increase the number of epochs.
> 
> The cake dataset has about 50 images which are 50 x 40 epochs = 2000 iterations. With 12 images, it has only 12x40 = 480 iterations.
> 
> Quality will improve over time. The result that shows on the website is trained with 4000 epochs.

I increase the training epochs. The results are much better. Thank you.
