### ISSUE TITLE
real-time rendering issue

### ISSUE THREAD

**Issue by jason718** [nex-mpi/nex-code#21]
For real-time rendering, is it true that H_i(v) is first offline-computed on the reference view v (pre-defined), and then warped to new views (unknown)? which mean there is no network inference in the real-time rendering stage.

is it possible to share the code of the online viewer (webgl)?

**Comment by bruinxiong** [comment]
Is there any plan to share the code of real-time rendering with webgl ?

**Comment by pureexe** [comment]
Here is the code of the WebGL

https://github.com/nex-mpi/nex-mpi.github.io/tree/main/viewer

you might want to look into 

https://github.com/nex-mpi/nex-mpi.github.io/blob/main/viewer/js/scene_learned_basis8.js

which the place the fragment shader was implemented.

**Comment by bruinxiong** [comment]
@pureexe Thanks to your instant reply. It's wonderful !

**Comment by pureexe** [comment]
> which mean there is no network inference in the real-time rendering stage.

The network output is precomputed as texture files. There has no network inference on real-time rendering.
