### ISSUE TITLE
Incorrect Colmap Option for Training 

### ISSUE THREAD

**Issue by ddxue** [nex-mpi/nex-code#3]
Thanks for the repo!

In `utils/colmap_runner.py` the `--output_path` option is added when `--export_path` should be specified.
```
  cmd("colmap mapper \
    --database_path " + dataset + "/database.db \
    --image_path " + dataset + "/images \
    --Mapper.ba_refine_principal_point 1 \
    --Mapper.num_threads 16 \
    --Mapper.extract_colors 0 \
    --output_path " + dataset + "/sparse")
```
should be 
```
  cmd("colmap mapper \
    --database_path " + dataset + "/database.db \
    --image_path " + dataset + "/images \
    --Mapper.ba_refine_principal_point 1 \
    --Mapper.num_threads 16 \
    --Mapper.extract_colors 0 \
    --export_path " + dataset + "/sparse")
```

**Comment by pureexe** [comment]
[COLMAP's cli docs](https://colmap.github.io/cli.html) already mention to using `--output_path`

![](https://i.imgur.com/j7SX53i.png)

the reason that you have to use `--export_path` is your COLMAP is too old. You should update your COLMAP.  

See, [COLMAP installation](https://colmap.github.io/install.html)

------
Difference between COLMAP 3.4 and COLMAP 3.6 
In our experiment, we use COLMAP 3.6
![](https://i.imgur.com/5dhAq4W.png)
