### ISSUE TITLE
Demo can not find files

### ISSUE THREAD

**Issue by MrGTAmodsgerman** [nex-mpi/nex-code#31]
![grafik](https://user-images.githubusercontent.com/19436774/132062111-ebe096f9-4abf-485c-9033-80535c688df9.png)

I tried it with 2 different sets of photos and it still fails.

**Comment by pureexe** [comment]
![image](https://user-images.githubusercontent.com/1303847/132643917-a9848aa0-b9cc-4c33-ba34-a896b436ae37.png)

Input image doesn't have good inital pair. 

Try to capture in front facting, something like this.

![image](https://user-images.githubusercontent.com/1303847/132644181-8be177f4-3589-4fe6-be73-f429d189f1d2.png)

See this video, start at 1:34
https://youtu.be/LY6MgDUzS3M?t=94

**Comment by MrGTAmodsgerman** [comment]
Ok sorry for the late answer. GitHub didn't sended any notifications. 
Ok, i tried it now with a less photogrammetry approach. Now it actually didn't crashed. Not the result i was expecting but i think i will get better one with several more attempts. Thanks.
