### ISSUE TITLE
Evaluation results for trex

### ISSUE THREAD

**Issue by mods333** [nex-mpi/nex-code#33]
Thank you sharing this amazing work. If you have them, could you share the rendered test images for the trex scene like you have for the other scenes here : https://drive.google.com/corp/drive/folders/1OLSy326rxCKMYRo4K7S27ew9D8NzfJo4

**Comment by pureexe** [comment]
I added trex to that directory. 

Sorry for the missing file.

**Comment by mods333** [comment]
Thanks a lot!
