### ISSUE TITLE
low quality outputs

### ISSUE THREAD

**Issue by sonnysorry** [nex-mpi/nex-code#34]
Hello and thanks for sharing this nice work! I 've been trying to make better outputs with nex but the only thing I got was low-quality output. 

I trained 2k-images with this code.

`python train.py -scene ${PATH_TO_SCENE} -model_dir ${MODEL_TO_SAVE_CHECKPOINT} -http -layers 12 -sublayers 6 -hidden 256`

but I got output-images like these. (the images which are automatically created in video_output directory after training )  

Even I created a dataset following the images collection method shown in LLFF and successfully installed Colmap and other requirements as well, I have no idea what's wrong with it. 

If there is any other way to get better outputs, please help me out. :)

and my environments are like those below.
RTX-2080Ti
Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Ubuntu 18.04.
CUDA Toolkit 10.2

Thanks

**Comment by pureexe** [comment]
There are 2 things that I can get from your output.

# 1. Your capture method is not ideal. 

Please do not rotate while capture, just moves a camera side by side. 

See, LLFF video on 1:36
https://youtu.be/LY6MgDUzS3M?t=96
[![image](https://user-images.githubusercontent.com/1303847/137726744-205e3af8-4e8d-4566-9b16-201d314d7b8b.png)](https://youtu.be/LY6MgDUzS3M?t=96)

# 2. need more offset

if the black color around the edge still occur in the scene, add `-offset 200` into the command line when call train.py

The default value is 200. You can increase the number but it might cause out of memory.

Let's see if it solve the problem or not
Cheer 😊

**Comment by sonnysorry** [comment]
Thank you! I got better output images.

I created a data set without rotating the camera and added -offset 300 command  (it is the maximum value under my training environment.) and I got outputs with fewer black parts. 

and I got one more question! Is there any option for getting output image with higher resolution?

I trained with 2048 x 1065 images but got 202x132 images.

Thanks.

**Comment by pureexe** [comment]
Size of output image is controlled by 2 parameters 
`-llff_width` and `-scale`

`-llff_width` tells how the width of the output image. default value is `-llff_width 1008` it will automatically calculate the scale of output images. In this case, it should output 1008/2048 = 0.4921. 

I'm not sure why your output is 202x132. 

you may try to provide `-scale 0.5` it should be output image with with 1024px.

**Comment by sonnysorry** [comment]
It works very well! Thanks for your help :)
