### ISSUE TITLE
generated MPIs cannot be seen on mobile

### ISSUE THREAD

**Issue by shamafiras** [nex-mpi/nex-code#37]
Hey,

I'm able to open the demos you generated on my mobile phone. 
however, I'm not able to see my own generated MPIs on my mobile. They simply do not show up, I only see the slider of layers.
I'm hosted my MPI on the web, and used the same viewer you use for mobile. textures are all loaded, but then it does not show anything.
Do you I need to do any further modification on the MPI in order to view it on mobile web ?
Thanks for your support and great work

Firas

**Comment by pureexe** [comment]
Your mobile phone might not have enough memory. 

Try open lower resolution on your mobile phone. 

See this comment about how to get lower resolution mpi by down scaling.

https://github.com/nex-mpi/nex-code/issues/10#issuecomment-834143720

**Comment by shamafiras** [comment]
Thanks for the quick response. 
In fact, after debugging the issue, it turns out the width of images files exceeded 4096pxls (due to use of default web_width=16000).
It is easily fixed after using any number below 4096, which is a limitation on my mobile.
Thanks, and keep up the good work.
