### ISSUE TITLE
Shiny Dataset Download

### ISSUE THREAD

**Issue by dogyoonlee** [nex-mpi/nex-code#47]
After Download the shiny datasets through **one-drive link**, I can't decompress the `zip` file.

To extract the file, I repaired the compressed file through following command.

`zip -FF my_zip --out my_zip_ver2.zip`

But, the file still have some problems after repairing.

When I decompress the repaired file, there is the log file which notice the error logs.

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/62277785/152927219-2866c021-cc57-4eec-8fe2-da7b51ad4deb.png">
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/62277785/152927233-b76a1daf-ad43-4492-bacf-3bae21710c17.png">

+ many files does not exist.

1062 files does not exist.

Is there any problem with the uploaded file?

Or how to download and extract the complete dataset?

I tried download on OSX and Ubuntu, but both failed.

Do I have to use window to download the file?

**Comment by pureexe** [comment]
Maybe the zip file is too large. you can try to download each subfolder instead or download it via the google drive link.

**Comment by dogyoonlee** [comment]
@pureexe 
Thanks a lot!! 
Solved.
