### ISSUE TITLE
Question about viewing direction, basis function, gpu memory

### ISSUE THREAD

**Issue by bring728** [nex-mpi/nex-code#51]
All 3d points along one ray have the same viewing direction. So when rendering, isn't it enough to input only one viewing direction rather than input all duplicate viewing directions into the basis function?

Below is the result I checked by myself. out2 is the basis function value.
![image](https://user-images.githubusercontent.com/24850969/157226983-eefe2836-421d-4c14-9469-946496128640.png)

As you can see, all 32 values have the same value of 0.1176. Since the input is the same, the output is of course the same.
My question is, do I really need to waste network memory? Instead of having 32 inputs, isn't it enough to have just 1 input?

**Comment by pureexe** [comment]
The viewing direction is the same as long the ray. The same viewing direction also produces the same basis value.

Our code is not focusing on performance. feel free to improve it.

**Comment by bring728** [comment]
i See. Thank you for answer. I was wondering if there might be another reason.
